language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install libuv-dev libqt4-dev libqt4-private-dev
  - git submodule update --init --recursive

script:
  - ./build.sh
