language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

sudo: required

before_install:
  - apt-get -qq update
  - git submodule update --init --recursive
  - apt-get -qq -y install libuv-dev libqt4-dev libqt4-private-dev

script:
  - ./build.sh
